[package]
authors = ["Elliott Linder <elliott.darfink@gmail.com>"]
name = "packet-derive"
version = "0.1.0"

[dependencies]
syn = "0.15"
quote = "0.6"

[dev-dependencies.muonline-packet]
path = "../muonline-packet"
features = ["serialize"]

[lib]
proc-macro = true
