[package]
authors = ["Elliott Linder <elliott@linder.bz>"]
name = "muonline-packet_serialize"
version = "0.1.0"

[dependencies]
byteorder = "1.2"
num-traits = "0.2"
serde = "1.0"
serde_derive = "1.0"
typenum = "1.10"

[dev-dependencies]
bincode = "1.0"
